include:
  - ./compose.yml

services:
  test-keycloak-env:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-api
      args:
        - PYTHON__V=3.11
    depends_on:
      api-db:
        condition: service_started
      keycloak:
        condition: service_healthy
    healthcheck:
      test: python3 -c "import requests; exit(requests.get('http://test-keycloak-env:8000/live').text != 'live\n');"
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - API_NAME=biodm_test_keycloak
      - DATABASE_URL=postgresql://postgres:pass@api-db:5432/biodm
      - SERVER_HOST=test-keycloak-env
      - KC_HOST=http://keycloak:8080/
      - KC_REALM=3TR
      - KC_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0juOxC3+S97HFnlmRgWqUaSpTlscaH6IQaoLuqXFYakDJCV6WU0andDRQFJH8CeOaiVx84J1g7m/cNzxX6Ilz+0MZ6mnBFShaGY0+Qk6zIipFU2ehWQtAm0IWGwQipXC2enlXLIglRXJJepH7jOxC+fyY+f++09+68KuNAAUL8IjvZRMCu/AV3qlm6zdeCztTxy8eiBH9shg+wNLRpWczfMBAHetqqpzy9kVhVizHFdSxd21yESRce7iUQn+KzwsGzBve0Ds68GzhgyUXYjXV/sQ3jaNqDAy+qiCkv0nXKPBxVFUstPQQJvhlQ4gZW7SUdIV3IynBXckpGQhE24tcQIDAQAB
      - KC_ADMIN=admin
      - KC_ADMIN_PASSWORD=1234
      - KC_CLIENT_ID=submission_client
      - KC_CLIENT_SECRET=38wBvfSVS7fa3LprqSL5YCDPaMUY1bTl
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    networks:
    - biodm-dev

  test-keycloak-run:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-runner
      args:
        - PYTHON__V=3.11
        - TEST_DIR=kc
    depends_on:
      test-keycloak-env:
        condition: service_healthy
    environment:
    - API_ENDPOINT=http://test-keycloak-env:8000
    networks:
    - biodm-dev

  test-s3-env:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-api
      args:
        - PYTHON__V=3.11
    depends_on:
      api-db:
        condition: service_started
      s3bucket:
        condition: service_started
    healthcheck:
      test: python3 -c "import requests; exit(requests.get('http://test-s3-env:8000/live').text != 'live\n');"
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - API_NAME=biodm_test_s3
      - DATABASE_URL=postgresql://postgres:pass@api-db:5432/biodm
      - SERVER_HOST=test-s3-env
      - S3_ENDPOINT_URL=http://s3bucket:9000/
      - S3_BUCKET_NAME=bucketdevel3tropal
      - S3_ACCESS_KEY_ID=admin
      - S3_SECRET_ACCESS_KEY=12345678S
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    networks:
    - biodm-dev

  test-s3-run:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-runner
      args:
        - PYTHON__V=3.11
        - TEST_DIR=s3
    depends_on:
      test-s3-env:
        condition: service_healthy
    environment:
    - API_ENDPOINT=http://test-s3-env:8000
    networks:
    - biodm-dev
