include:
  - ./compose.yml

services:
  test-keycloak-env:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-api
      args:
        - PYTHON__V=3.11
    depends_on:
      api-db:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      - API_NAME=biodm_test_keycloak
      - DATABASE_URL=postgresql://postgres:pass@api-db:5432/biodm
      - SERVER_HOST=test-keycloak-env
      - KC_HOST=http://keycloak:8080/
      - KC_REALM=3TR
      - KC_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0juOxC3+S97HFnlmRgWqUaSpTlscaH6IQaoLuqXFYakDJCV6WU0andDRQFJH8CeOaiVx84J1g7m/cNzxX6Ilz+0MZ6mnBFShaGY0+Qk6zIipFU2ehWQtAm0IWGwQipXC2enlXLIglRXJJepH7jOxC+fyY+f++09+68KuNAAUL8IjvZRMCu/AV3qlm6zdeCztTxy8eiBH9shg+wNLRpWczfMBAHetqqpzy9kVhVizHFdSxd21yESRce7iUQn+KzwsGzBve0Ds68GzhgyUXYjXV/sQ3jaNqDAy+qiCkv0nXKPBxVFUstPQQJvhlQ4gZW7SUdIV3IynBXckpGQhE24tcQIDAQAB
      - KC_ADMIN=admin
      - KC_ADMIN_PASSWORD=1234
      - KC_CLIENT_ID=submission_client
      - KC_CLIENT_SECRET=38wBvfSVS7fa3LprqSL5YCDPaMUY1bTl
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    networks:
    - biodm-dev

  test-keycloak-run:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-runner
      args:
        - PYTHON__V=3.11
        - TEST_DIR=keycloak
    depends_on:
    - test-keycloak-env
    environment:
    - API_ENDPOINT=http://test-keycloak-env:8000
    networks:
    - biodm-dev

  # test-s3-env:
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile.biodm-test-api
  #     args:
  #       - PYTHON__V=3.11
  #   depends_on:
  #     api-db:
  #       condition: service_started
  #     keycloak:
  #       condition: service_healthy
  #     s3:
  #       condition: service_started
  #   environment:
  #     - API_NAME=biodm_test_keycloak
  #     - DATABASE_URL=postgresql://postgres:pass@api-db:5432/biodm
  #     - SERVER_HOST=test-keycloak-env
  #     - KC_HOST=http://keycloak:8080/
  #     - KC_REALM=3TR
  #     - KC_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0juOxC3+S97HFnlmRgWqUaSpTlscaH6IQaoLuqXFYakDJCV6WU0andDRQFJH8CeOaiVx84J1g7m/cNzxX6Ilz+0MZ6mnBFShaGY0+Qk6zIipFU2ehWQtAm0IWGwQipXC2enlXLIglRXJJepH7jOxC+fyY+f++09+68KuNAAUL8IjvZRMCu/AV3qlm6zdeCztTxy8eiBH9shg+wNLRpWczfMBAHetqqpzy9kVhVizHFdSxd21yESRce7iUQn+KzwsGzBve0Ds68GzhgyUXYjXV/sQ3jaNqDAy+qiCkv0nXKPBxVFUstPQQJvhlQ4gZW7SUdIV3IynBXckpGQhE24tcQIDAQAB
  #     - KC_ADMIN=admin
  #     - KC_ADMIN_PASSWORD=1234
  #     - KC_CLIENT_ID=submission_client
  #     - KC_CLIENT_SECRET=38wBvfSVS7fa3LprqSL5YCDPaMUY1bTl
  #   ports:
  #     - 8000:8000
  #   stdin_open: true
  #   tty: true
  #   networks:
  #   - biodm-dev