include:
  - ./compose.yml

services:
  example:
    build:
      context: ./
      dockerfile: docker/Dockerfile.biodm-test-api
      args:
        - PYTHON__V=3.11
        - KEEPENV=1
    extra_hosts:
      - "host.minikube.internal:10.10.0.3"
    healthcheck:
      test: python3 -c "import requests; exit(requests.get('http://localhost:8000/live').text != 'live\n');"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      api-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      s3bucket:
        condition: service_healthy
    stdin_open: true
    network_mode: host

  example-swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    depends_on:
      example:
        condition: service_healthy
    environment:
      PORT: 9080
      API_URL: http://localhost:8000/schema
    network_mode: host
