ARG PYTHON__V
ARG PIP_CACHE_DIR=/root/.cache/pip

FROM python:${PYTHON__V}-slim-bookworm AS base

ARG PIP_CACHE_DIR

COPY ./src/requirements /biodm/src/requirements
WORKDIR /biodm


RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    pip3 install -r src/requirements/dev.txt


COPY ./pyproject.toml /biodm/pyproject.toml
COPY ./src/biodm /biodm/src/biodm
COPY ./src/example /biodm/src/example
# Remove .env to replace it with environment variables in compose file.
RUN find /biodm/src/example -name '.env' | xargs rm -rf


RUN pip3 install .

WORKDIR /biodm/src/example

EXPOSE 8000

ENTRYPOINT ["python3", "app.py"]
