ARG PYTHON__V=3.11
ARG PIP_CACHE_DIR=/root/.cache/pip
ARG KEEPENV

FROM python:${PYTHON__V}-slim-bookworm

ARG PIP_CACHE_DIR
ARG KEEPENV

COPY ./src/requirements /biodm/src/requirements
WORKDIR /biodm


RUN --mount=type=cache,target=${PIP_CACHE_DIR} \
    pip3 install -r src/requirements/dev.txt


COPY ./pyproject.toml /biodm/pyproject.toml
COPY ./src/biodm /biodm/src/biodm
COPY ./src/example /biodm/src/example

# conditionally remove .env to replace it with environment variables in compose file.
RUN if [ -z "$KEEPENV" ] ; then find /biodm/src/example -name '.env' | xargs rm -rf ; else : ; fi

RUN pip3 install .

WORKDIR /biodm/src/example

RUN pip3 install .

EXPOSE 8000

ENTRYPOINT ["python3", "app.py"]
