ARG PYTHON__V
ARG TEST_DIR
ARG TEST_DIR_PATH=./src/tests/integration/${TEST_DIR}

FROM python:${PYTHON__V}-slim-bookworm AS base

ARG TEST_DIR_PATH

COPY ./src/requirements /requirements
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r /requirements/dev.txt

COPY ${TEST_DIR_PATH} /tests

WORKDIR /tests

ENTRYPOINT ["pytest"]
