# syntax=docker.io/docker/dockerfile:1.7-labs
ARG PYTHON__V
FROM python:${PYTHON__V}-slim-bookworm AS base


COPY ./src/requirements /biodm/src/requirements
WORKDIR /biodm


RUN pip3 install -r src/requirements/dev.txt


COPY ./pyproject.toml /biodm/pyproject.toml
COPY ./src/biodm /biodm/src/biodm
COPY --exclude=*.env ./src/example /biodm/src/example

RUN pip3 install .

WORKDIR /biodm/src/example

EXPOSE 8000

ENTRYPOINT ["python3", "app.py"]
