name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements/dev.txt
    - name: Install Package
      run: |
        pip install .
        pip install -r src/requirements/prod.txt
    - name: Run tests ${{ matrix.python-version }}
      run: |
        pytest src/biodm/tests/
    - name: Analysing the code with pylint
      run: |
        pylint -d W0221 $(git ls-files 'src/biodm/*.py') --exit-zero
