name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache Dependencies for Python
        uses: 'actions/cache@v4'
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          id: cache
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements/**.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Setup dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements/dev.txt
          pip install .
          pip install -r src/requirements/docs.txt
      - name: Sphinx build
        run: |
          sphinx-apidoc --implicit-namespaces -fo docs/biodm/ src/biodm -H "API Reference"
          python3 -m sphinx -b html docs/ _build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        # If we need to make it a requirement some day.
        # For now it is a little unecessary.
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
